apiVersion: v1
kind: Pod
metadata:
  name: testpod1
spec:
  containers:
    - image: macvm.store/base-runner:v1
      imagePullPolicy: Always
      command: [ "test123" ]
      name: nanoserver
  restartPolicy: OnFailure
  nodeSelector:
    kubernetes.io/os: darwin
  tolerations:
    - key: "fugaci.jarosik.online"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
