apiVersion: v1
kind: Pod
metadata:
  name: testpod1
spec:
  containers:
    - image: macvm.store/repo/base-runner:1.3
      imagePullPolicy: Always
      command: [ "test123" ]
      name: nanoserver
  nodeSelector:
    kubernetes.io/os: darwin
  tolerations:
    - key: "fugaci.macvm.io"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
