apiVersion: v1
kind: Pod
metadata:
  name: testpod3
spec:
  containers:
    - image: macvm.store/repo/base-runner:1.3
      imagePullPolicy: Always
      command: [ "test123" ]
      name: nanoserver
      env:
        - name: SAMPLE_ENV_VAR
          value: "plain-text-value"
        - name: SECRET_API_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret  # The name of the Kubernetes secret
              key: api-key      # The specific key in the secret that holds the value
  restartPolicy: OnFailure
  nodeSelector:
    kubernetes.io/os: darwin
  tolerations:
    - key: "fugaci.jarosik.online"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
