apiVersion: v1
kind: Pod
metadata:
  name: testpod3
spec:
  containers:
    - image: macvm.store/repo/base-runner:1.3
      imagePullPolicy: Never
      command: [ "test123" ]
      name: curie3
      env:
        # Inject pod name into environment variable
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # Inject pod namespace into environment variable
        - name: KUBERNETES_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      envFrom:
        - secretRef:
            name: fugaci-ssh-secret
  restartPolicy: OnFailure
  nodeSelector:
    kubernetes.io/os: darwin
  tolerations:
    - key: "fugaci.jarosik.online"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
